### PR TITLE
Added spanish words =)

### PR DESCRIPTION
**Pull request by ElenaMLopez**
Added 'por-cojones' and 'por-mis-huevos' 
Maybe littel long but very used in Spanish. Hope you like it!!! :)

The litteral tanslation is:
'por-cojones': for-balls (masculine attribute) 
'por-mis-huevos': for my balls (masculine attribute)
The both means something similar to : Because I say so.
Hope I'ts usefull!!

### CODE REVIEW

**Comment by SaraVieira** [comment]
@ElenaMLopez This is awesome ! Thank you so much ! 🙏

Can you please just add them with trabslations to the readme ? 😀

**Comment by ElenaMLopez** [comment]
Can I eddit the readme to add this words too?

**Comment by SaraVieira** [comment]
Of course you can  😄

**Comment by pi0** [comment]
@ElenaMLopez Think words DB is now moved into a new home [SaraVieira/curse-words](https://github.com/SaraVieira/curse-words) so this PR may be retargeted there.

**Pull request closed without merging**
