### PR TITLE
Add Persian curse words

### PR DESCRIPTION
**Pull request by erbesharat**
Just added some Persian(Farsi) curse words 😄

### CODE REVIEW

**Comment by SaraVieira** [comment]
This is amazing ! Thank you so much @erbesharat 🎉

**Comment by erbesharat** [comment]
@SaraVieira I think there is a problem, README has been updated but there isn't any Persian curse word in index.js.

**Comment by lovelldies** [comment]
@erbesharat you would need to update the test.js file with your words.
https://github.com/SaraVieira/postcss-caralho/blob/master/test/test.js

**Comment by SaraVieira** [comment]
I screwed up the merge, sorry :(

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by erbesharat** [comment]
@lovelldies I've written tests for my words, it looks like Sara did something wrong :D

**Comment by SaraVieira** [comment]
@erbesharat No need , I fixed my dumbness 🎉 

And merged 👍 

Thank you so much @erbesharat !

**Pull request merged**
